Repository anz-bank/sysl, pull requests merged in 2020-08, with the labels that each got.

#1021 Update lint job in GitHub workflow and fix lint issues
  .github/workflows/go.yml
  .golangci.yml
  cmd/sysl/cmd_diagram.go
  docs/CONTRIBUTING.md
  pkg/database/db_test_utils.go
  pkg/diagrams/plantuml.go
  pkg/exporter/swagger_exporter_test.go
  pkg/importer/importer_test.go
  pkg/parse/Parser_test.go
  pkg/parse/listener_impl.go
Labels: testing

#1025 Remove code generate examples to resolve cyclic dependency
  demo/Readme.md
  demo/examples/Code-Generation/Intro.md
  demo/examples/Code-Generation/Makefile
  demo/examples/Code-Generation/README.md
  demo/examples/Code-Generation/api/swagger2-spec/jsonplaceholder.json
  demo/examples/Code-Generation/api/sysl/simple.sysl
  demo/examples/Code-Generation/gen/jsonplaceholder/service.go
  demo/examples/Code-Generation/gen/jsonplaceholder/types.go
  demo/examples/Code-Generation/gen/simple/requestrouter.go
  demo/examples/Code-Generation/gen/simple/servicehandler.go
  demo/examples/Code-Generation/gen/simple/serviceinterface.go
  demo/examples/Code-Generation/gen/simple/types.go
  demo/examples/Code-Generation/generate.sh
  demo/examples/Code-Generation/internal/server/server.go
  demo/examples/Code-Generation/main.go
  demo/examples/Code-Generation/ordering.yaml
  demo/examples/Code-Generation/pkg/defaultcallback/defaultcallback.go
  demo/examples/Code-Generation/simple.sysl
  demo/examples/Code-Generation/test.sh
  docs/website/content/docs/byexample/code-generation.md
  go.mod
  go.sum
Labels: code health

#1027 Add unit tests to pkg/arrai
  pkg/arrai/Makefile
  pkg/arrai/util_test.arrai
Labels: testing

#1032 Union fixing
  pkg/grammar/SyslParser.g4
  pkg/grammar/sysl_parser.go
  pkg/grammar/syslparser_base_listener.go
  pkg/grammar/syslparser_listener.go
  pkg/parse/listener_impl.go
  pkg/parse/tests/union.sysl
  pkg/parse/tests/union.sysl.golden.textpb
  unsorted/sysl_js/SyslParser.g4
Labels: breaking-change
