Repository anz-bank/sysl, pull requests merged in 2020-02, with the labels that each got.

#554 Add command sysl env
  cmd/sysl/cmd_env.go
  cmd/sysl/cmd_runner.go
  docs/website/content/docs/reference_guide/outputs.md
Labels: ready-for-review

#522 Issue 473
  cmd/sysl/datamodel_test.go
  cmd/sysl/datamodelview.go
  cmd/sysl/datamodelview_test.go
  cmd/sysl/sysl_test.go
  tests/data.sysl
  tests/primitive-alias-model-golden.puml
Labels: WIP

#548 Add sysl modules docs
  demo/examples/Modules/foreign_import_swagger.yaml
  demo/examples/Modules/model_with_deps.sysl
  demo/examples/Modules/moredeps/moredeps.sysl
  demo/examples/ordering.yaml
  docs/language_guide.md
  docs/website/content/docs/byexample/data-model-diagrams.md
  docs/website/content/docs/byexample/integration-diagrams.md
  docs/website/content/docs/byexample/modules.md
  docs/website/content/docs/byexample/rest-and-http.md
  docs/website/content/docs/byexample/sequence-diagrams.md
  docs/website/static/assets/byexample/images/data-model-diagrams9.svg
  docs/website/static/assets/byexample/images/integration-diagrams8.svg
  docs/website/static/assets/byexample/images/sequence-diagrams7.svg
  model_with_deps.sysl
  pkg/mod/fs.go
Labels: documentation

#573 Update CI workflows to use GoReleaser
  .github/workflows/.goreleaser-go-darwin.yml
  .github/workflows/.goreleaser-go-linux.yml
  .github/workflows/.goreleaser-go-windows.yml
  .github/workflows/.goreleaser.yml
  .github/workflows/go-darwin.yml
  .github/workflows/go-linux.yml
  .github/workflows/go-windows.yml
  .github/workflows/release.yml
  Makefile
  scripts/build.sh
  scripts/coverage-windows.bat
  scripts/test-gosysl.bat
  scripts/test-with-coverage-windows.bat
Labels: ready-for-review

#571 update releasing.md
  .github/workflows/.goreleaser.yml
  .github/workflows/release.yml
  docs/blog/setup.md
  docs/releasing.md
  scripts/release.sh
Labels: ready-for-review

#590 feat: trigger generate-tag workflow on specified PR merged
  .gitattributes
  .github/PULL_REQUEST_TEMPLATE/new_release.md
  .github/PULL_REQUEST_TEMPLATE/pull_request.md
  .github/goreleaser_configs/.goreleaser-go-darwin.yml
  .github/goreleaser_configs/.goreleaser-go-linux.yml
  .github/goreleaser_configs/.goreleaser-go-windows.yml
  .github/goreleaser_configs/.goreleaser.yml
  .github/workflows/generate-tag.yml
  .github/workflows/go-darwin.yml
  .github/workflows/go-linux.yml
  .github/workflows/go-windows.yml
  .github/workflows/release.yml
  CHANGELOG/CHANGELOG-0.1.md
  CHANGELOG/CHANGELOG-0.2.md
  CHANGELOG/CHANGELOG-0.3.md
  CHANGELOG/CHANGELOG-0.4.md
  CHANGELOG/CHANGELOG-0.5.md
  docs/blog/setup.md
  docs/releasing.md
Labels: ready-for-review

#630 #625 Fix error panic: runtime error: invalid memory address or nil pointer dereference
  cmd/sysl/datamodelview.go
Labels: bug
